# Generated by Django 3.2.5 on 2022-02-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalapp', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
