# Generated by Django 3.2.5 on 2022-02-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalapp', '0004_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
